apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: apps
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: "1"
            memory: "100Mi"
          requests:
            cpu: "1"
            memory: "100Mi"
        image: nginx:1.14.2
        ports:
        - containerPort: 80

